### ISSUE TITLE
Does not seem to work form MELPA

### ISSUE THREAD

**Issue by tee3** [the-frey/cyberpunk-2019#4]
This theme does not seem to work when installed from MELPA.  It is downloaded and byte-compiled, but does not appear in the list of themes in `M-x load-theme`.

Using Emacs 26.1 and installing with `M-x package-install RET cyberpunk-2019-theme`.  Note that I also have the original `cyberpunk-theme` installed, but removing it did not change this behavior.

```
Contacting host: melpa.org:443
Generating autoloads for cyberpunk-2019-theme.el...done
Wrote /Users/tsc/.emacs.d/elpa/cyberpunk-2019-theme-20190228.1453/cyberpunk-2019-theme-autoloads.el [2 times]
Checking /Users/tsc/.emacs.d/elpa/cyberpunk-2019-theme-20190228.1453... [2 times]
Compiling /Users/tsc/.emacs.d/elpa/cyberpunk-2019-theme-20190228.1453/cyberpunk-2019-theme.el...done
Wrote /Users/tsc/.emacs.d/elpa/cyberpunk-2019-theme-20190228.1453/cyberpunk-2019-theme.elc
Checking /Users/tsc/.emacs.d/elpa/cyberpunk-2019-theme-20190228.1453... [2 times]
```

**Comment by cyberoctopi** [comment]
Same issue for me. Also using 26.1

**Comment by the-frey** [comment]
Is this the case after restarting emacs? Sometimes I have had to do that when installing themes... will try and replicate in the meantime.

Suspect I might not have seen it as I think I have an explicit `(load-theme 'cyberpunk-2019 t)` in my initfile...

**Comment by tee3** [comment]
Yes, restarting emacs does not fix the issue.  I am able to load the them it just does not appear in the list.

**Comment by l0rdn1bbl3r** [comment]
You can fix this by adding 
```
;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))
```
to cyberpunk-2019-theme.el  (Just have a look in any of the themes that load fine)
Afterwards call `update-file-autoloads` on the file.
After restarting emacs the theme will be found by `load-theme`. 

Sorry for the redundance. Just saw the the pull-request.
